DOCKER_FILE_PATH: /harness/harness-core/dockerization/change-data-capture/Dockerfile-change-data-capture-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/110-change-data-capture/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml
