DOCKER_FILE_PATH: /harness/harness-core/dockerization/event-server/Dockerfile-event-server-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/350-event-server/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml
