BEGIN;
CREATE TABLE IF NOT EXISTS DEPLOYMENT_STEP (
    ID TEXT NOT NULL,
    ACCOUNT_ID TEXT NOT NULL,
    APP_ID TEXT NOT NULL,
    STEP_NAME TEXT NOT NULL,
    STEP_TYPE TEXT NOT NULL,
    STATUS VARCHAR(20),
    FAILURE_DETAILS TEXT,
    START_TIME BIGINT,
    END_TIME BIGINT,
    DURATION BIGINT,
    IS_WORKFLOW boolean,
    EXECUTION_ID TEXT NOT NULL,
    APPROVED_BY TEXT,
    APPROVAL_TYPE TEXT,
    APPROVED_AT BIGINT,
    APPROVAL_COMMENT TEXT,
    APPROVAL_EXPIRY BIGINT,
    MANUAL_INTERVENTION boolean,
    PRIMARY KEY(ID,START_TIME)
);
COMMIT;


SELECT CREATE_HYPERTABLE('DEPLOYMENT_STEP','start_time',if_not_exists => TRUE,migrate_data => true,chunk_time_interval => 86400000000);

CREATE OR REPLACE FUNCTION unix_now() returns BIGINT LANGUAGE SQL STABLE as $$ SELECT extract(epoch from now())::BIGINT $$;

SELECT set_integer_now_func('DEPLOYMENT_STEP', 'unix_now');
SELECT add_retention_policy('DEPLOYMENT_STEP', BIGINT '86400000000');
