BEGIN;
CREATE TABLE IF NOT EXISTS DEPLOYMENT_STEP (
    ID TEXT NOT NULL,
    ACCOUNT_ID TEXT NOT NULL,
    APP_ID TEXT NOT NULL,
    STEP_NAME TEXT NOT NULL,
    STEP_TYPE TEXT NOT NULL,
    STATUS VARCHAR(20),
    FAILURE_DETAILS TEXT,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    DURATION BIGINT,
    STAGE_NAME TEXT,
    EXECUTION_ID TEXT NOT NULL,
    APPROVED_BY TEXT,
    APPROVAL_TYPE TEXT,
    APPROVED_AT TIMESTAMP,
    APPROVAL_COMMENT TEXT,
    APPROVAL_EXPIRY TIMESTAMP,
    MANUAL_INTERVENTION boolean,
    PRIMARY KEY(ID,START_TIME)
);
COMMIT;


SELECT CREATE_HYPERTABLE('DEPLOYMENT_STEP','start_time',if_not_exists => TRUE,migrate_data => true,chunk_time_interval => INTERVAL '1 day');

SELECT add_retention_policy('DEPLOYMENT_STEP', INTERVAL '1 day');
