DOCKER_FILE_PATH: /harness/harness-core/332-ci-manager/build/container/Dockerfile-ci-manager-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/332-ci-manager/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml
