DOCKER_FILE_PATH: /harness/harness-core/pipeline-service/build/container/Dockerfile-pipeline-service-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/pipeline-service/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml
