# Dropwizard config
server:
  allowedMethods: ["GET", "POST"]
  adminConnectors: []
  applicationConnectors:
    - type: http
      port: 3460
      maxRequestHeaderSize: 100KiB
  rootPath: /api
  maxThreads: 1024

logging:
  type: external

# Delegate Config
accountId: kmpySmUISimoRrJL6NL73w
delegateToken: 2f6b0988b6fb3370073c3d0505baee59
managerUrl: https://localhost:9090/api/
verificationServiceUrl: https://localhost:7070/verification/
cvNextGenUrl: https://localhost:6060/cv/api/
logStreamingServiceBaseUrl: http://localhost:8079
heartbeatIntervalMs: 50000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
managerTarget: localhost:9880
managerAuthority: localhost
queueFilePath: ../eventQueue
grpcServiceEnabled: false
grpcServiceConnectorPort: 8080
clientToolsDownloadDisabled: true
installClientToolsInBackground: false
delegateName: local-delegate

# Required for local development as manger uses self-signed cert
trustAllCertificates: true