mongo:
  uri: mongodb://localhost:27017/idp-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  transactionsEnabled: false
  aliasDBName: idp-harness
  traceMode: DISABLED
  maxOperationTimeInMillis: 300000

server:
  applicationConnectors:
    - type: http
      port: 12003
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 12004
  requestLog:
    appenders: []
  maxThreads: 1024

eventsFramework:
  redis:
    sentinel: false
    masterName: "test"
    redisUrl: "redis://localhost:6379"
    sentinelUrls:
      - "redis://redis1:26379"
      - "redis://redis2:26379"
      - "redis://redis3:26379"
    envNamespace: ""
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true
    userName: ""
    password: ""
    sslConfig:
      enabled: false
      CATrustStorePath: "/tmp/ca_trust_store"
      CATrustStorePassword: ""

redisLockConfig:
  sentinel: false
  masterName: "test"
  redisUrl: "redis://localhost:6379"
  sentinelUrls:
    - "redis://redis1:26379"
    - "redis://redis2:26379"
    - "redis://redis3:26379"
  envNamespace: ""
  readMode: MASTER
  nettyThreads: 16
  useScriptCache: true
  userName: ""
  password: ""

pmsSdkGrpcServerConfig:
  connectors:
    - port: 12501
      secure: true
      keyFilePath: key.pem
      certFilePath: cert.pem
    - port: 12502

pmsGrpcClientConfig:
  target: localhost:12011
  authority: localhost

shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-false}

cacheConfig:
  cacheBackend: REDIS
  cacheNamespace: ""
  disabledCaches: [ ]
  enterpriseCacheEnabled: true

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

distributedLockImplementation: REDIS

logStreamingServiceConfig:
  baseUrl: http://localhost:8079
  serviceToken: token

ngManagerServiceHttpClientConfig:
  baseUrl: http://localhost:7457/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

managerClientConfig:
  baseUrl: http://localhost:3457/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

backstageHttpClientConfig:
  baseUrl: http://localhost:7007/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

ngManagerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
managerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
backstageServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
idpServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
jwtAuthSecret: dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq
jwtIdentityServiceSecret: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=
idpEncryptionSecret: q7YdsdUoXTit5nqdBR1LdKQXE3beIGE6yiseIPM1WKg_iFE5C4oRxi1_Ao6XcKZvhCbtgZQliOkUO1cu
pipelineServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
jwtExternalServiceSecret: nhUmut2NMcUnsR01OgOz0e51MZ51AqUwrOATJ3fJ

managerTarget: localhost:9880
managerAuthority: localhost

onboardingModuleConfig:
  descriptionForEntitySelected: A YAML file will be created for each service inside your Git repository. An example of what the files will look like is shown below
  descriptionForSampleEntity: Because you didn't choose any Harness services to import in the previous step, an example Harness service catalog-info.yaml will be created inside your Git repository as shown below
  useGitServiceGrpcForSingleEntityPush: true
  tmpPathForCatalogInfoYamlStore: /tmp/idp-catalog-onboarding
  catalogInfoLocationDefaultPath: /.harness-idp-entities
  harnessCiCdAnnotations:
    projectUrl: https://localhost:8181/ng/account/accountIdentifier/home/orgs/orgIdentifier/projects/projectIdentifier/details
    serviceUrl: https://localhost:8181/ng/account/accountIdentifier/cd/orgs/orgIdentifier/projects/projectIdentifier/services/serviceIdentifier

gitManagerGrpcClientConfig:
  target: localhost:13001
  authority: localhost

accessControlClient:
  enableAccessControl: false
  accessControlServiceConfig:
    baseUrl: http://localhost:9006/api/
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  accessControlServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

backstageSaToken: ""
backstageSaCaCrt: ""
backstageMasterUrl: ""
backstagePodLabel: ""

provisionModuleConfig:
  triggerPipelineUrl: ""

env: ""
prEnvDefaultBackstageNamespace: ""

backstageAppBaseUrl: https://localhost:3000
backstagePostgresHost: ""

delegateSelectorsCacheMode: redis # in-memory or redis

proxyAllowList:
  services:
    manager:
      proxyPath: v1/idp-proxy-service/manager
      clientConfig:
        baseUrl: http://localhost:3457/api/
        connectTimeOutSeconds: 15
        readTimeOutSeconds: 15
      secret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
      allowList:
        - /users/validate-support-user
    ng-manager:
      proxyPath: v1/idp-proxy-service/ng-manager
      clientConfig:
        baseUrl: http://localhost:7457/
        connectTimeOutSeconds: 15
        readTimeOutSeconds: 15
      secret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
      allowList:
        - /user/aggregate
        - /aggregate/acl/usergroups
        - /token/validate

shouldConfigureWithNotification: ${SHOULD_CONFIGURE_WITH_NOTIFICATION:-false}

notificationClient:
  messageBroker:
    type: MONGO
    uri: mongodb://localhost:27017/notification
    connectTimeout: 30000
    serverSelectionTimeout: 90000
    socketTimeout: 360000
    maxConnectionIdleTime: 600000
    connectionsPerHost: 300
  httpClient:
    baseUrl: http://localhost:9005/api/
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  secrets:
    notificationClientSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

notificationConfigs:
  pluginRequestsNotificationSlack: https://hooks.slack.com/services/dummy/dummy/dummy

pipelineServiceClientConfig:
  baseUrl: http://localhost:12001/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

scorecardScoreComputationIteratorConfig:
  threadPoolCount: 5
  enabled: false
  targetIntervalInSeconds: 43200 #12 hours in seconds

tiServiceConfig:
  internalUrl: ""
  baseUrl: http://localhost:8078
  globalToken: "78d16b66-4b4c-11eb-8377-acde48001122"

cpu: 2
scoreComputerThreadsPerCore: 2

streamPerServiceConfiguration: ${PIE_STREAM_PER_SERVICE:- false}

auditClientConfig:
  baseUrl: http://localhost:9005/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

enableAudit: false

internalAccounts:
  - kmpySmUISimoRrJL6NL73w

segmentConfiguration:
  enabled: false
  url: "segment_url_place_holder"
  apiKey: "segment_api_key"
  certValidationRequired: false