DOCKER_FILE_PATH: /harness/harness-core/idp-service/build/container/Dockerfile-idp-service-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/idp-service/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml