apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: template-service
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.commonLabels }}
  labels:
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      {{- include "template-service.selectorLabels" . | nindent 6 }}
