# Default values for sto-manager
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  commonAnnotations: {}
  commonLabels: {}
  loadbalancerURL: "https://test"
  delegate:
    airgapped: false
  imagePullSecrets: []
  istio:
    enabled: false
    gateway:
      create: true
      port: 443
      protocol: HTTPS
    hosts:
    - '*'
    strict: true
    tls:
      credentialName: ""
    virtualService:
      hosts:
      - ''
      gateways: []
  ingress:
    enabled: false
    objects:
      annotations: {}
    hosts:
      - 'my-host.example.org'
    tls:
      enabled: false
      secretName: harness-cert
  stackDriverLoggingEnabled: false
  database:
    postgres:
      ## - installed = true if installed within cluster
      installed: true
      ## - protocol to use for connection
      protocol: postgres
      ## - host array for external
      hosts:
        - postgres:5432
      ## - secret name containing external values
      secretName: ""
      ## - key within secret containing username
      userKey: ""
      ## - key within secret containing password
      passwordKey: ""
      ## - extra arguments set to connection string
      extraArgs: ""
    mongo:
      installed: true
      protocol: mongodb
      # --  provide default values if mongo.installed is set to false
      hosts: []
      secretName: ""
      userKey: ""
      passwordKey: ""
      extraArgs: ""
    timescaledb:
      installed: true
      protocol: "jdbc:postgresql"
      # --  provide default values if mongo.installed is set to false
      hosts:
        - timescaledb-single-chart:5432
      secretName: ""
      userKey: ""
      passwordKey: ""
      extraArgs: ""
      certName: ""
      certKey: ""
    redis:
      installed: true
      protocol: "redis"
      # --  provide default values if redis.installed is set to false
      hosts:
        - redis:6379
      secretName: "redis-secret"
      userKey: "redis-user"
      passwordKey: "redis-password"
      extraArgs: ""
  opa:
    enabled: false


replicaCount: 1
maxSurge: 100%
maxUnavailable: 0
java:
  memory: 2500
  memoryLimit: 600
image:
  registry: docker.io
  repository: harness/stomanager-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "80900-000"
  digest: ""
  imagePullSecrets: []
waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""
    imagePullSecrets: []
securityImage:
  image:
    registry: docker.io
    repository: harness/sto-plugin
    pullPolicy: IfNotPresent
    tag: 1.19.0
    digest: ""
    imagePullSecrets: []
addOnImage:
  image:
    registry: docker.io
    repository: harness/ci-addon
    pullPolicy: IfNotPresent
    tag: "1.16.26"
    digest: ""
    imagePullSecrets: []
leImage:
  image:
    registry: docker.io
    repository: harness/ci-lite-engine
    pullPolicy: IfNotPresent
    tag: "1.16.26"
    digest: ""
    imagePullSecrets: []
s3UploadImage:
  image:
    registry: docker.io
    repository: plugins/s3
    pullPolicy: IfNotPresent
    tag: "1.2.7"
    digest: ""  
    imagePullSecrets: []
mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password
timescaleSecret:
  password:
    name: harness-secrets
    key: timescaledbPostgresPassword
nameOverride: ""
fullnameOverride: ""
ngServiceAccount: "test"
redislabsCATruststore: "test"
defaultInternalImageConnector: "account.harnessImage"
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

probes:
  livenessProbe:
    httpGet:
      path: /health/liveness
      port: http
    timeoutSeconds: 2
    periodSeconds: 5
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /health
      port: http
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 5
  startupProbe:
    httpGet:
      path: /health
      port: http
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 25
service:
  annotations: {}
  type: ClusterIP
  port: 7090
  grpcport: 9979
ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources:
  # limits:
  #   memory: 128Mi
  requests:
    cpu: 1
    memory: 3Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPU: ""
  targetMemory: ""
stoServiceGlobalToken:
  name: harness-secrets
  key: stoAppHarnessToken
nodeSelector: {}
tolerations: []
affinity: {}
# Commented out at request of Will as not needed.
# env:
#   secrets:
#   config:
#     APP_ENABLE_UI: "true"
#     APP_TOKEN_JWT_SECRET: test
#     APP_INTERNAL_TOKEN_JWT_SECRET: test
#     STO_SERVICE_GLOBAL_TOKEN: "token"
additionalConfigs: {}

# extraVolumes:
#   - name: volume-test
#     configMap:
#       name: test-config
#       # readOnly: true
extraVolumes: []

# extraVolumeMounts:
#   - name: volume-test
#     mountPath: /opt/harness/config
extraVolumeMounts: []

lifecycleHooks: {}
# lifecycleHooks:
#   postStart:
#     exec:
#       command:
#   preStop:
#     exec:
#       command:
virtualService:
  annotations: {}
ingress:
  annotations: {}