DOCKER_FILE_PATH: /harness/harness-core/access-control/build/container/Dockerfile-accesscontrol-service-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/access-control/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml
