# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

FROM us.gcr.io/platform-205701/cie-agent-harness-core-jdk11:latest as builder

RUN mkdir -p /app
COPY . /app
WORKDIR /app

ENV BUILD_PURPOSE=DEVELOPMENT
RUN chmod +x \
 /app/product/log-service/build/feature_build.sh \
 /app/scripts/bazel/generate_credentials.sh \
 && /app/scripts/bazel/generate_credentials.sh \
 && /app/product/log-service/build/feature_build.sh

FROM us.gcr.io/platform-205701/ubi/ubi-go:8.8
# Copy go binary
COPY log-service_/log-service /usr/local/bin/log-service
RUN ls log-service_/log-service /usr/local/bin/log-service
USER root
RUN chown -R 65534:65534 --from=builder /usr/local/bin
USER 65534
WORKDIR /usr/local/bin
CMD ["/usr/local/bin/log-service", "server"]