# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

# To be used when building in CIE
FROM golang:1.20-bullseye as builder
RUN mkdir -p /app
ARG GCP_KEY
ENV SERVICE_NAME="log-service"
COPY . /app

WORKDIR /app

ENV BUILD_PURPOSE=DEVELOPMENT
ENV PLATFORM="jenkins"

RUN chmod +x \
    /app/product/log-service/build/feature_build.sh \
    && /app/product/log-service/build/feature_build.sh $GCP_KEY \

ENV CONTEXT_PATH $BAZEL_BIN

FROM us.gcr.io/platform-205701/harness/ubi8/go1:1.21 as base
# Copy go binary
ENV CONTEXT_PATH $BAZEL_BIN
RUN echo $CONTEXT_PATH
RUN cd /
COPY /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/execroot/harness_monorepo/bazel-out/k8-fastbuild/bin/product/log-service/log-service_/log-service /usr/local/bin/log-service
USER root
RUN chown -R 65534:65534 /usr/local/bin
USER 65534:65534
WORKDIR /usr/local/bin
CMD ["/usr/local/bin/log-service", "server"]

FROM base as saas
RUN if [ "$INCLUDE_SAAS_APM" == "true" ] ; then /opt/harness/inject-saas-apm-bins-into-dockerimage.sh; fi && rm -rf /opt/harness/inject-saas-apm-bins-into-dockerimage.sh
USER root
