# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

# To be used when building in CIE
FROM us.gcr.io/platform-205701/harness/ubi8:8.8 as builder

# Install curl
RUN apt-get update -y && apt-get install -y curl

# Download the Go distribution archive
#RUN curl -O https://dl.google.com/go/go1.19.8.linux-amd64.tar.gz

RUN mkdir -p /app
ARG GCP_KEY
ENV SERVICE_NAME="log-service"
COPY . /app

WORKDIR /app

ENV BUILD_PURPOSE=DEVELOPMENT
ENV PLATFORM="jenkins"

RUN chmod +x \
    /app/product/log-service/build/feature_build.sh \
    && /app/product/log-service/build/feature_build.sh $GCP_KEY \

ENV CONTEXT_PATH $BAZEL_BIN

FROM builder as base
# Copy go binary

COPY --from=builder $BAZEL_BIN /usr/local/bin/log-service
USER root
RUN chown -R 65534:65534 /usr/local/bin
USER 65534:65534
WORKDIR /usr/local/bin
CMD ["/usr/local/bin/log-service", "server"]

FROM base as saas
RUN if [ "$INCLUDE_SAAS_APM" == "true" ] ; then /opt/harness/inject-saas-apm-bins-into-dockerimage.sh; fi && rm -rf /opt/harness/inject-saas-apm-bins-into-dockerimage.sh
USER root
