DOCKER_FILE_PATH: /harness/harness-core/product/ci/scm/docker/Dockerfile
HELM_CHART_SOURCE_DIRECTORY: harness-core/product/ci/scm/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml
