# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2019 as core


FROM mcr.microsoft.com/powershell:nanoserver-1809
USER ContainerAdministrator

COPY --from=core /windows/system32/netapi32.dll /windows/system32/netapi32.dll
ADD ci-addon_/ci-addon.exe C:/addon.exe
ADD split_tests.exe C:/harness/
ENV GODEBUG=netdns=go

RUN setx /M PATH "%PATH%;C:\Program Files\PowerShell"
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENTRYPOINT [ "C:\\addon.exe" ]