DOCKER_FILE_PATH: /harness/harness-core/template-service/build/container/Dockerfile-template-service-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/template-service/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml

