# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
# Run:  docker build -t <image>:tag -f Dockerfile-task . --build-arg TARGETARCH=$ARCH
#       TARGETARCH: amd64, arm64

FROM redhat/ubi8-minimal:8.4

LABEL name="harnessdev/delegate-runner" \
      vendor="Harness" \
      maintainer="Harness"

RUN microdnf update \
  && microdnf install --nodocs \
    procps \
    hostname \
    lsof \
    findutils \
    tar \
  && rm -rf /var/cache/yum \
  && microdnf clean all \
  && mkdir -p /opt/harness/

ARG TARGETARCH=arm64

COPY scripts /opt/harness/
COPY taskfile /opt/harness/taskfile

WORKDIR /opt/harness

RUN mkdir -m 777 -p client-tools/kubectl/v1.13.2 \
    && curl -s -L -o client-tools/kubectl/v1.13.2/kubectl https://app.harness.io/public/shared/tools/kubectl/release/v1.13.2/bin/linux/$TARGETARCH/kubectl \
    && mkdir -m 777 -p client-tools/go-template/v0.4 \
    && curl -s -L -o client-tools/go-template/v0.4/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4/bin/linux/$TARGETARCH/go-template \
    && mkdir -m 777 -p client-tools/go-template/v0.4.1 \
    && curl -s -L -o client-tools/go-template/v0.4.1/go-template https://app.harness.io/public/shared/tools/go-template/release/v0.4.1/bin/linux/$TARGETARCH/go-template

RUN chmod -R 755 /opt/harness \
    && chgrp -R 0 /opt/harness  \
    && chmod -R g=u /opt/harness \
    && chown -R 1001 /opt/harness

COPY --from=adoptopenjdk/openjdk11:jre-11.0.14_9-ubi-minimal /opt/java/openjdk/ /opt/java/openjdk/

ENV HOME=/opt/harness
ENV JAVA_HOME=/opt/java/openjdk/
ENV PATH="$JAVA_HOME/bin:${PATH}"

COPY ./TaskApp_deploy.jar ./task.jar

USER 1001

CMD [ "./start.sh" ]