BUILD_SCRIPT_PATH: product/log-service/build/feature_build.sh
DOCKER_FILE_PATH: /harness/harness-core/product/log-service/docker/Dockerfile-log-service-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/product/log-service/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml