# Default values for harness-manager
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  commonAnnotations: {}
  commonLabels: {}
  kubeVersion: ""
  loadbalancerURL: ""
  database:
    postgres:
      ## - installed = true if installed within cluster
      installed: true
      ## - protocol to use for connection
      protocol: postgres
      ## - host array for external
      hosts:
        - postgres:5432
      ## - secret name containing external values
      secretName: ""
      ## - key within secret containing username
      userKey: ""
      ## - key within secret containing password
      passwordKey: ""
      ## - extra arguments set to connection string
      extraArgs: ""
    mongo:
      installed: true
      protocol: mongodb
      # --  provide default values if mongo.installed is set to false
      hosts: []
      secretName: ""
      userKey: ""
      passwordKey: ""
      extraArgs: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              MONGO_USER: ""
              MONGO_PASSWORD: ""
        secretManagement: 
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                MONGO_USER:
                  name: ""
                  property: ""
                MONGO_PASSWORD:
                  name: ""
                  property: ""
    timescaledb:
      installed: true
      protocol: "jdbc:postgresql"
      sslEnabled: false
      # --  provide default values if mongo.installed is set to false
      hosts:
        - timescaledb-single-chart:5432
      secretName: ""
      userKey: ""
      passwordKey: ""
      extraArgs: ""
      certName: ""
      certKey: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              TIMESCALEDB_USERNAME: ""
              TIMESCALEDB_PASSWORD: ""
              TIMESCALEDB_SSL_ROOT_CERT: ""
        secretManagement: 
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                TIMESCALEDB_USERNAME:
                  name: ""
                  property: ""
                TIMESCALEDB_PASSWORD:
                  name: ""
                  property: ""
                TIMESCALEDB_SSL_ROOT_CERT:
                  name: ""
                  property: ""
    redis:
      installed: true
      protocol: "redis"
      # --  provide default values if redis.installed is set to false
      hosts:
        - redis:6379
      secretName: "redis-secret"
      userKey: "redis-user"
      passwordKey: "redis-password"
      extraArgs: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              REDIS_USERNAME: ""
              REDIS_PASSWORD: ""
        secretManagement: 
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                REDIS_USERNAME:
                  name: ""
                  property: ""
                REDIS_PASSWORD:
                  name: ""
                  property: ""
  ingress:
    # -- create ingress objects
    enabled: false
    # -- set ingress object classname
    className: harness
    # -- set host of ingressObjects
    hosts:
      - my-host.example.org
    # -- set tls for ingress objects
    tls:
      enabled: true
      secretName: ''
    # -- add annotations to ingress objects
    objects:
      annotations: {}
  istio:
    # -- create virtualServices objects
    enabled: false
    # -- create gateway and use in virtualservice
    gateway:
      create: false
    # -- if gateway not created, use specified gateway and host
    virtualService:
      gateways:
      hosts:
  mongoSSL: false
  license:
    cg: ''
    ng: ''
    secrets:
      kubernetesSecrets:
        - secretName: ""
          keys:
            CG_LICENSE: ""
      secretManagement: 
        externalSecretsOperator:
          - secretStore:
              name: ""
              kind: ""
            remoteKeys:
              CG_LICENSE:
                name: ""
                property: ""
  cd:
    enabled: false
  ci:
    enabled: false
  sto:
    enabled: false
  srm:
    enabled: false
  ngcustomdashboard:
    enabled: false
  ff:
    enabled: false
  ccm:
    enabled: false
  saml:
    autoaccept: false
  gitops:
    enabled: false
  opa:
    enabled: false
  ng:
    enabled: true
  cg:
    enabled: false
  ngGitSync:
    enabled: false
  chaos:
    enabled: false
  useImmutableDelegate: "false"
  smtpCreateSecret:
    enabled: false
    SMTP_PASSWORD: ""
    SMTP_HOST: ""
    SMTP_USERNAME: ""
    SMTP_USE_SSL: "true"
    SMTP_PORT: "465"
    secrets:
      kubernetesSecrets:
        - secretName: ""
          keys:
            SMTP_USERNAME: ""
            SMTP_PASSWORD: ""
            SMTP_HOST: ""
            SMTP_PORT": ""
            SMTP_USE_SSL: ""
      secretManagement: 
        externalSecretsOperator:
          - secretStore:
              name: ""
              kind: ""
            remoteKeys:
              SMTP_USERNAME:
                name: ""
                property: ""
              SMTP_PASSWORD:
                name: ""
                property: ""
              SMTP_HOST:
                name: ""
                property: ""
              SMTP_PORT:
                name: ""
                property: ""
              SMTP_USE_SSL:
                name: ""
                property: ""
  ha: false

redis:
  protocol: ""
  hosts: []
  secretName: ""
  userKey: ""
  passwordKey: ""
  extraArgs: ""
  secrets:
    kubernetesSecrets:
      - secretName: ""
        keys:
          REDIS_USERNAME: ""
          REDIS_PASSWORD: ""
    secretManagement: 
      externalSecretsOperator:
        - secretStore:
            name: ""
            kind: ""
          remoteKeys:
            REDIS_USERNAME:
              name: ""
              property: ""
            REDIS_PASSWORD:
              name: ""
              property: ""

timescaledb:
  # -- TimescaleDB host names
  hosts: []
  # -- Enable TimescaleDB SSL
  # sslEnabled: false
  # -- TimescaleDB secrets
  secrets:
    kubernetesSecrets:
      - secretName: ""
        keys:
          TIMESCALEDB_USERNAME: ""
          TIMESCALEDB_PASSWORD: ""
          TIMESCALEDB_SSL_ROOT_CERT: ""
    secretManagement: 
      externalSecretsOperator:
        - secretStore:
            name: ""
            kind: ""
          remoteKeys:
            TIMESCALEDB_USERNAME:
              name: ""
              property: ""
            TIMESCALEDB_PASSWORD:
              name: ""
              property: ""
            TIMESCALEDB_SSL_ROOT_CERT:
              name: ""
              property: ""
mongo:
  protocol: ""
  hosts: []
  extraArgs: ""
  secrets:
    kubernetesSecrets:
      - secretName: ""
        keys:
          MONGO_USER: ""
          MONGO_PASSWORD: ""
    secretManagement: 
      externalSecretsOperator:
        - secretStore:
            name: ""
            kind: ""
          remoteKeys:
            MONGO_USER:
              name: ""
              property: ""
            MONGO_PASSWORD:
              name: ""
              property: ""

replicaCount: 1
maxSurge: 1
maxUnavailable: 0

image:
  registry: docker.io
  repository: harness/migrator-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "100578-000"
  digest: ""
  imagePullSecrets:
  - gcr-io-secret

waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""
    imagePullSecrets: []

initContainer:
  image:
    registry: docker.io
    repository: busybox
    pullPolicy: IfNotPresent
    tag: latest
    digest: ""

config:
  ALLOWED_ORIGINS: ""
  DELEGATE_METADATA_URL: ""
  WATCHER_METADATA_URL: ""
  LOG_STREAMING_SERVICE_BASEURL:
  LOG_STREAMING_SERVICE_EXTERNAL_URL:
  ATMOSPHERE_BACKEND: REDIS
  BACKGROUND_SCHEDULER_CLUSTERED: "true"
  CACHE_BACKEND: REDIS
  CAPSULE_JAR: migrator-capsule.jar
  IMMUTABLE_DELEGATE_ENABLED:
  DELEGATE_SERVICE_TARGET: harness-manager:9879
  DELEGATE_SERVICE_AUTHORITY: harness-manager:9879
  DISTRIBUTED_LOCK_IMPLEMENTATION: REDIS
  DEPLOY_MODE: KUBERNETES_ONPREM
  DISABLE_NEW_RELIC: "true"
  ENABLE_G1GC: "true"
  EXTERNAL_GRAPHQL_RATE_LIMIT: 500
  GITOPS_SERVICE_CLIENT_BASEURL:
  HAZELCAST_NAMESPACE:
  HAZELCAST_SERVICE: harness-manager
  HZ_CLUSTER_NAME: harness-manager
  LOGGING_LEVEL: "INFO"
  MEMORY: "2048"
  REDIS_SENTINEL: "true"
  REDIS_URL: 'redis://localhost:6379'
  REDIS_MASTER_NAME: 'harness-redis'
  REDIS_SENTINELS:
  SERVER_PORT: "9080"
  SERVICE_ACC: /opt/harness/svc/service_acc.json
  VERSION: 1.0.100440
  NG_MANAGER_BASE_URL:
  AUDIT_CLIENT_BASEURL:
  TEMPLATE_SERVICE_ENDPOINT:
  PIPELINE_SERVICE_CLIENT_BASEURL:
  NG_MANAGER_CLIENT_BASEURL:
  ACCESS_CONTROL_ENABLED: "true"
  ACCESS_CONTROL_BASE_URL:
  EVENTS_FRAMEWORK_REDIS_SENTINELS:
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: 'harness-redis'
  EVENTS_FRAMEWORK_USE_SENTINEL: "true"
  EVENTS_FRAMEWORK_AVAILABLE_IN_ONPREM: "true"
  EVENTS_FRAMEWORK_REDIS_URL: 'redis://localhost:6379'
  HARNESS_ENABLE_NG_AUTH_UI_PLACEHOLDER: "true"
  MONGO_SSL_CONFIG: "false"
  ENABLE_ITERATORS: 'true'
  ITERATOR_CONFIG_PATH: '/opt/harness/config'
  LICENSE_INFO:

iteratorConfig:
  alertReconciliation:
    enabled: true
    threadPoolSize: 3
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 600
    throttleIntervalInSeconds: 0
  artifactCollection:
    enabled: true
    threadPoolSize: 20
    threadPoolIntervalInSeconds: 10
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 60
    throttleIntervalInSeconds: 0
  artifactCleanup:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 300
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 7200
    throttleIntervalInSeconds: 0
  eventDelivery:
    enabled: true
    threadPoolSize: 25
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 5
    throttleIntervalInSeconds: 0
  instanceSync:
    enabled: true
    threadPoolSize: 10
    threadPoolIntervalInSeconds: 30
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 600
    throttleIntervalInSeconds: 0
  licenseExpiryCheck:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 30
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 3600
    throttleIntervalInSeconds: 0
  approvalPolling:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 10
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 60
    throttleIntervalInSeconds: 0
  gcpBilling:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 1800
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 3600
    throttleIntervalInSeconds: 0
  segmentGroupEventJob:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 1800
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 86400
    throttleIntervalInSeconds: 0
  barrierInstanceMonitor:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 60
    throttleIntervalInSeconds: 0
  entityAuditRecordProcessor:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 30
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 1800
    throttleIntervalInSeconds: 0
  usageMetricsHandler:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 30
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 86400
    throttleIntervalInSeconds: 0
  resourceConstraintBackup:
    enabled: true
    threadPoolSize: 10
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 30
    throttleIntervalInSeconds: 0
  workflowExecutionMonitor:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 10
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 60
    throttleIntervalInSeconds: 0
  settingAttributeValidateConnectivity:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 600
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 10800
    throttleIntervalInSeconds: 0
  vaultSecretManagerRenewalHandler:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 5
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 31
    throttleIntervalInSeconds: 0
  settingAttributesSecretsMigrationHandler:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 30
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 1800
    throttleIntervalInSeconds: 0
  gitSyncEntityExpiryCheck:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 600
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 43200
    throttleIntervalInSeconds: 0
  exportExecutionsRequestHandler:
    enabled: true
    threadPoolSize: 3
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 1800
    throttleIntervalInSeconds: 0
  exportExecutionsRequestCleanupHandler:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 3600
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 2700
    throttleIntervalInSeconds: 0
  deploymentFreezeActivities:
    enabled: true
    threadPoolSize: 3
    threadPoolIntervalInSeconds: 0
    nextIterationMode: "THROTTLE"
    targetIntervalInSeconds: 0
    throttleIntervalInSeconds: 45
  deploymentFreezeDeactivation:
    enabled: true
    threadPoolSize: 3
    threadPoolIntervalInSeconds: 0
    nextIterationMode: "THROTTLE"
    targetIntervalInSeconds: 0
    throttleIntervalInSeconds: 45
  ceLicenceExpiryProcessor:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 86400
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 86400
    throttleIntervalInSeconds: 0
  deleteAccountIterator:
    enabled: false
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 18000
    throttleIntervalInSeconds: 0
  deletedEntityIterator:
    enabled: false
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 43200
    throttleIntervalInSeconds: 0
  resourceLookupTagLinkSync:
    enabled: true
    threadPoolSize: 1
    threadPoolIntervalInSeconds: 43200
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 43200
    throttleIntervalInSeconds: 0
  accessRequestHandler:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 5
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 15
    throttleIntervalInSeconds: 0
  scheduledTrigger:
    enabled: true
    threadPoolSize: 8
    threadPoolIntervalInSeconds: 0
    nextIterationMode: "THROTTLE"
    targetIntervalInSeconds: 0
    throttleIntervalInSeconds: 45
  ldapGroupScheduled:
    enabled: true
    threadPoolSize: 8
    threadPoolIntervalInSeconds: 0
    nextIterationMode: "THROTTLE"
    targetIntervalInSeconds: 0
    throttleIntervalInSeconds: 45
  encryptedDataLocalToGcpKmsMigrationHandler:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 30
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 72000
    throttleIntervalInSeconds: 0
  timeoutEngine:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 10
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 10
    throttleIntervalInSeconds: 0
  gitSyncPollingIterator:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 300
    throttleIntervalInSeconds: 0
  perpetualTaskAssignment:
    enabled: true
    threadPoolSize: 5
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 60
    throttleIntervalInSeconds: 0
  delegateDisconnectDetector:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 60
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 60
    throttleIntervalInSeconds: 0
  delegateTaskFail:
    enabled: true
    threadPoolSize: 2
    threadPoolIntervalInSeconds: 30
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 30
    throttleIntervalInSeconds: 0
  delegateTelemetryPublisherIteration:
    enabled: true
    threadPoolSize: 1
    threadPoolIntervalInSeconds: 600
    nextIterationMode: "TARGET"
    targetIntervalInSeconds: 86400
    throttleIntervalInSeconds: 0

mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password

timescaleSecret:
  password:
    name: harness-secrets
    key: timescaledbPostgresPassword

delegate_docker_image:
  image:
    registry: docker.io
    repository: harness/delegate
    tag: latest
    digest: ""

immutable_delegate_docker_image:
  image:
    registry: docker.io
    repository: harness/delegate
    tag: 22.12.77617
    digest: ""

upgrader_docker_image:
  image:
    registry: docker.io
    repository: harness/upgrader
    tag: latest
    digest: ""

appLogLevel: INFO

external_graphql_rate_limit: "500"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 65534
  runAsNonRoot: true

service:
  annotations: {}
  type: ClusterIP
  port: 9080
  grpcport: 9879

resources:
  limits:
    memory: 8192Mi
  requests:
    cpu: 2
    memory: 3000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPU: ""
  targetMemory: ""

nodeSelector: {}

tolerations: []

affinity: {}

migrator:
  mongodb:
    override: false
    protocol: mongodb
    hosts: []
    secretName: ""
    userKey: ""
    passwordKey: ""
    extraArgs: ""

# extraVolumes:
# - name: volume-test
#   configMap:
#     name: test-config
#     readOnly: true
extraVolumes: []

# extraVolumeMounts:
#   - name: test-volume-mount
#     mountPath: /opt/harness/config
extraVolumeMounts: []

# lifecycleHooks:
#   postStart:
#     exec:
#       command:
#   preStop:
#     exec:
#       command:

# extraEnvVars:
# - name: POD_NAME
#   valueFrom:
#     fieldRef:
#       fieldPath: metadata.name
extraEnvVars: []

virtualService:
  annotations: {}
ingress:
  annotations: {}

java17flags: ""

secrets:
  default:
    LOG_STREAMING_SERVICE_TOKEN: "c76e567a-b341-404d-a8dd-d9738714eb82"
    VERIFICATION_SERVICE_SECRET: "59MR5RlVARcdH7zb7pNx6GzqiglBmXR8"
    MONGO_SSL_CA_TRUST_STORE_PATH: "/opt/harness/keystore.jks"
    MONGO_SSL_CA_TRUST_STORE_PASSWORD: "password"
  kubernetesSecrets:
  - secretName: ""
    keys:
      LOG_STREAMING_SERVICE_TOKEN: ""
      VERIFICATION_SERVICE_SECRET: ""
  secretManagement: 
    externalSecretsOperator:
    - secretStore:
        name: ""
        kind: ""
      remoteKeys:
        LOG_STREAMING_SERVICE_TOKEN:
          name: ""
          property: ""
        VERIFICATION_SERVICE_SECRET:
          name: ""
          property: ""
