FROM redhat/ubi8:latest
CMD ["/bin/sh"]
#RUN apk update && apk upgrade && apk add openjdk11 && apk add --no-cache curl make bash libstdc++
RUN yum -y update && yum -y install curl libstdc++.i686 make bash

#Installing yq
RUN curl -L https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -o /usr/bin/yq && chmod +x /usr/bin/yq

RUN set -x \
    && mkdir -p /opt/harness/plugins \
    && chown -R 65534:65534 /opt/harness \
    && chmod -R 700 /opt/harness

WORKDIR /opt/harness

USER 65534