DOCKER_FILE_PATH: /harness/harness-core/ce-nextgen/build/container/Dockerfile-ce-nextgen-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/ce-nextgen/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml
