# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

# To be used when building in CIE

FROM us.gcr.io/platform-205701/ubi/ubi-java:latest as base

FROM base as onprem

USER root

# Add the capsule JAR and config.yml
COPY --chown=65534:65534 rest-capsule.jar /opt/harness/
COPY --chown=65534:65534 newrelic.yml /opt/harness/
COPY --chown=65534:65534 keystore.jks  /opt/harness/
COPY --chown=65534:65534 classpath_metadata.json /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 hazelcast.xml /opt/harness/
COPY --chown=65534:65534 redisson-jcache.yaml /opt/harness/
COPY --chown=65534:65534 protocol.info /opt/harness/

COPY --chown=65534:65534 scripts /opt/harness

RUN chmod +x /opt/harness/*.sh && chmod 700 -R /opt/harness/ && chown -R 65534:65534 /opt/harness/

CMD [ "./run.sh" ]

USER 65534

FROM base as saas

USER root

# Add the capsule JAR and config.yml
COPY --chown=65534:65534 rest-capsule.jar /opt/harness/
COPY --chown=65534:65534 newrelic.yml /opt/harness/
COPY --chown=65534:65534 keystore.jks  /opt/harness/
COPY --chown=65534:65534 classpath_metadata.json /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 hazelcast.xml /opt/harness/
COPY --chown=65534:65534 redisson-jcache.yaml /opt/harness/
COPY --chown=65534:65534 protocol.info /opt/harness/

COPY --chown=65534:65534 scripts /opt/harness

RUN chmod +x /opt/harness/*.sh && chmod 700 -R /opt/harness/ && chown -R 65534:65534 /opt/harness/

RUN curl -L https://harness.jfrog.io/artifactory/BuildsTools/docker/apm/appd/AppServerAgent-1.8-21.11.2.33305.zip > /opt/harness/AppServerAgent-1.8-21.11.2.33305.zip \
    && curl -LO https://harness.jfrog.io/artifactory/BuildsTools/docker/apm/overops/takipi-agent-latest.tar.gz && tar -xzf takipi-agent-latest.tar.gz -C /opt/harness \
    && rm -rf takipi-agent-latest.tar.gz \
    && curl -LO https://get.et.harness.io/releases/latest/nix/harness-et-agent.tar.gz && tar -xzf harness-et-agent.tar.gz -C /opt/harness \
    && rm -rf harness-et-agent.tar.gz \
    && curl -L https://github.com/inspectIT/inspectit-ocelot/releases/download/1.16.0/inspectit-ocelot-agent-1.16.0.jar > /opt/harness/inspectit-ocelot-agent-1.16.0.jar

RUN chmod -R +x /opt/harness/ \
    && chmod -R +x /opt/harness/takipi \
    && chmod 700 -R /opt/harness/ \
    && chown -R 65534:65534 /opt/harness/

CMD [ "./run.sh" ]

USER 65534
