apiVersion: v1
kind: Secret
metadata:
  name: batch-processing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "batch-processing.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- include "batch-processing.generateSecrets" (dict "ctx" $) | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: batch-processing-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "batch-processing.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- include "batch-processing.generateMountSecrets" (dict "ctx" $) | indent 2 }}