DOCKER_FILE_PATH: /harness/harness-core/dockerization/migrator/Dockerfile-migrator-multistage
HELM_CHART_SOURCE_DIRECTORY: harness-core/100-migrator/chart
VERSION_FILE: harness-core/980-commons/src/main/resources-filtered/versionInfo.yaml

